### PR TITLE
fix: don't require id for FIFO messages (Fixes #23)

### LINKED ISSUE #23: Requires id for FIFO queues
Hello!

I'm trying to send a message to a FIFO queues, which require de groupId and deduplicationId, but the package is requiring me to enter an ID which is never used.

My code: 

```js
const producer = Producer.create({
  queueUrl: 'https://sqs.us-east-1.amazonaws.com/xxxxxxxx/yyyyyyyyy.fifo',
  region: 'us-east-1'
})

const content = JSON.stringify({zzzzzzzz: 1})

const message = {
  body: content,
  id: 'woot',
  groupId: 'group1234',
  deduplicationId: shajs('sha256').update(content).digest('hex')
}

producer.send(message, err => {
  if (err) console.log(err)
})
```

Error: `Error: Object messages must have 'id' and 'body' props`
`at entryFromObject (/lib/producer.js:47:11)`

### PR DESCRIPTION
**Pull request by DiegoRBaquero**
According to the example in the docs, it isn't required.

If included, it should be used, if not, it should be the body.

### CODE REVIEW

**Comment by niklasR** [comment]
Hi @DiegoRBaquero, thanks for that.
I just had a look through the docs, and it seems to me like `id` isn't required for _any_ messages now.
I have just verified that by sending a message without an ID without issues.

I feel like this is a great opportunity to update this. What do you think?

File: lib/producer.js [hunk 1]
```diff
@@ -43,12 +43,20 @@ function isMessageAttributeValid(messageAttribute) {
...
+    throw new Error('Object messages must have \'id\' prop');
+  }
+    
+  if (message.deduplicationId && !message.groupId) {
+    throw new Error('FIFO Queue messages must have \'groupId\' prop');
   }
 
   var entry = {
-    Id: message.id,
+    Id: message.id || message.body,
```
Comment (niklasR) [inline lib/producer.js]: This change is not tested, and I'm not sure it's necessary? This would always assign an ID to any message, but this whole PR is about _not_ needing an id?

**Comment by DiegoRBaquero** [comment]
@niklasR I've remove that part, plus, Id is limited to 80 alphanumeric chars, body is not. It would have failed in many scenarios.

**Comment by niklasR** [comment]
@DiegoRBaquero Great, thanks. For the `deduplicationId ` and the `groupId` we also assert that they are valid (see lines 87ff & 95ff). Do you think that would make sense for the `id` here, as well?

**Comment by DiegoRBaquero** [comment]
I've added assert for type :)

**Comment by niklasR** [comment]
Thanks. If we can test that like [the others](https://github.com/bbc/sqs-producer/blob/master/test/producer.js#L334), I'll be happy to merge it :)
